version: '3.8'

services:

  fastapi:
    build: ./fastapi
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://test:test@db/fastapi-boilerplate
      - SECRET_KEY=1a30c4915edcc7136a258172641950fe0a7bed774a83418a
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.1-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fastapi-boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: