version: '3.8'

services:
  fastapi:
    build: ./fastapi
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://test:test@db/fastapi-boilerplate
      - SECRET_KEY=super-secret-key # Change this to a random string
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.1-alpine
    expose:
      - "5433" # Publishes 5433 to other containers but not to host machine
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fastapi-boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p 5433 # Custom port for postgres to avoid conflicts with host machine

volumes:
  postgres_data: