"""second commit

Revision ID: 779fc2b27598
Revises: f040eb720fa9
Create Date: 2022-12-22 19:15:45.513879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779fc2b27598'
down_revision = 'f040eb720fa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
